### ISSUE TITLE
Why WakeOnLan connects to Google Servers / Firebase?

### ISSUE THREAD

**Issue by just-Nob** [Florianisme/WakeOnLan#25]
Hi Florian,

why your WOL tool connects to Google Servers (see F-Droid's Anti-Features)?
I guess this will send some data to Google that the user (e.g. me) don't want to give to Google.

**Comment by Florianisme** [comment]
Hi, it probably says that, because I'm using the Wearable library by Google to communicate with the Watch App.

I can however assure you that no data is actively sent to Google by this app. I have not implemented any collection of metrics at all.

As this app is open source you could either self-compile if you really want to certain or use the APKs from the Releases here on Github :)

**Comment by just-Nob** [comment]
Hi Florian,
sorry, I wanted to answer earlier.
Anyway, thx for your answer!
