### ISSUE TITLE
Removed from Google Play Store?

### ISSUE THREAD

**Issue by gsingh93** [Florianisme/WakeOnLan#47]
Hi, was this app removed from the play store? I went to install it on a new phone and I saw it wasn't available. 

I can install it from GH for now, but it would be more convenient if it was in the play store.

**Comment by Florianisme** [comment]
Hi, yes unfortunately my Play Developer Account was locked because Google made it mandatory for all developers who published paid apps to publicly display their full private address. Because I did not want that they locked it. Maybe Ill look into other app stores or an in-app update functionality from Github.

**Comment by dw5** [comment]
also google play will kick you out if you don't update apps often, so thats annoying...
Not much alternative stores exists, Huawei one that can be installed on anything is very aggressive on personal info, even more than what google wants, Samsung store and others are often Vendor exclusive so not good.
Anyway for direct from github updates take a look at this https://github.com/ImranR98/Obtainium

I'm also developing my own app store, due to reasons, but i'm not super duper Android developer (can do only super basics, not fan of android studio, and just find android dev confusing), I'm better at backend and web side of things, but yeah obtainium and fdroid compatible repo is the best way to go for now it seems.

**Comment by Obi-Wahn** [comment]
Is F-Droid a possibility? i don't know what advantages or disadvantages there are...

**Comment by dw5** [comment]
https://apt.izzysoft.de/fdroid/index/apk/de.florianisme.wakeonlan


also use Droidify, a more modern F-Droid client, plus has that repo ready to use, so less hassle adding it (if I remember correctly, otherwise add yourself)
